@startuml

class Mahasiswa {
- id
- name
- function()
}

class MataKuliah{
- id
- name
- test()
}

Mahasiswa "*..1" - "*..*" MataKuliah

class Testing{
+fillable
-fillable
-function()
-name()
}

@enduml 